[package]
org = "ballerina"
name = "io"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["io", "json", "xml", "csv", "file"]
repository = "https://github.com/ballerina-platform/module-ballerina-io"
icon = "resources/icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/io-native-@project.version@.jar"
version = "@project.version@"


[[platform.java11.dependency]]
path = "../test-utils/build/libs/io-test-utils-@project.version@.jar"
scope = "testOnly"
version = "@project.version@"
