[package]
org = "ballerina"
name = "io"
version = "1.8.0-20250311-0838-1e3b7b9e"
authors = ["Ballerina"]
keywords = ["io", "json", "xml", "csv", "file"]
repository = "https://github.com/ballerina-platform/module-ballerina-io"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "io-native"
path = "../native/build/libs/io-native-1.8.0-20250311-0838-1e3b7b9e.jar"
version = "1.8.0-20250311-0838-1e3b7b9e"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "io-compiler-plugin"
version = "1.8.0-20250311-0838-1e3b7b9e"
path = "../compiler-plugin/build/libs/io-compiler-plugin-1.8.0-20250311-0838-1e3b7b9e.jar"

[[platform.java21.dependency]]
path = "../test-utils/build/libs/io-test-utils-1.8.0-20250311-0838-1e3b7b9e.jar"
scope = "testOnly"
version = "1.8.0-20250311-0838-1e3b7b9e"
