[package]
org = "ballerina"
name = "io"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../native/build/libs/io-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "io"
version = "@project.version@"


[[platform.java11.dependency]]
path = "../test-utils/build/libs/io-test-utils-@project.version@.jar"
groupId = "org.ballerinalang.stdlib.io"
scope = "testOnly"
artifactId = "io"
version = "@project.version@"
