[package]
org = "ballerina"
name = "io"
version = "1.0.1"
authors = ["Ballerina"]
keywords = ["io", "json", "xml", "csv", "file"]
repository = "https://github.com/ballerina-platform/module-ballerina-io"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/io-native-1.0.1.jar"
version = "1.0.1"


[[platform.java11.dependency]]
path = "../test-utils/build/libs/io-test-utils-1.0.1.jar"
scope = "testOnly"
version = "1.0.1"
