[plugin]
id = "io-compiler-plugin"
class = "io.ballerina.stdlib.io.compiler.IOCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/io-compiler-plugin-1.8.0-20250311-0838-1e3b7b9e.jar"
